### ISSUE TITLE
我想用自己的数据进行训练，似乎出现了一些错误

### ISSUE THREAD

**Issue by zxupstar** [zhouyongxiu/PytorchExample#2]
tensor(0.4565, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.6296, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch [64/64], Loss: -1.31608212, Time: 18.8sec!
有loss为负值

Acc: 0.0000
tensor(0.4456, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4184, device='cuda:0', grad_fn=<NllLossBackward>)
Epoch [13/64], Loss: 0.53375417, Time: 18.7sec!
有的准确率为0

是因为我数据的问题吗？

**Comment by zhouyongxiu** [comment]
原因可能是使用nllloss作为损失函数引起的，如果你训练的是简单的分类任务，直接用CrossEntropyLoss损失函数就够了

**Comment by lb1234564** [comment]
我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
layer1~4都正常打印了

**Comment by zhouyongxiu** [comment]
> 我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了



> 我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了

有完整的打印信息吗

**Comment by lb1234564** [comment]
[error.txt](https://github.com/zhouyongxiu/PytorchExample/files/7570153/error.txt)
这是完整的打印信息

**Comment by lb1234564** [comment]
附件里有完整的打印信息





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouyongxiu/PytorchExample"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouyongxiu/PytorchExample] 我想用自己的数据进行训练，似乎出现了一些错误 (#2)





  
我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了
   
我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了
  
有完整的打印信息吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
